In [1]:
import numpy as np

In [16]:
def naive_add_matrix_an_vector(x, y):
    assert len(x.shape) == 2
    assert len(y.shape) == 1
    assert x.shape[1] == y.shape[0]
    
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] += y[j]

    return x

In [48]:
y = np.array([12, 3, 6, 14])
x = np.array([[5, 78, 2, 34],
             [6, 79, 3, 35],
             [7, 70, 4, 36]])

a = x = np.array([[1, 78, 2, 34],
                 [6, 1, 3, 35],
                 [7, 70, 4, 36]])

In [18]:
naive_add_matrix_an_vector(x, y)

array([[17, 81,  8, 48],
       [18, 82,  9, 49],
       [19, 73, 10, 50]])

In [33]:
y = np.random.random((64, 3, 32, 10))
x = np.random.random((32, 10))
z = np.maximum(x, y)

In [34]:
z

array([[[[0.78449976, 0.96807171, 0.76011387, ..., 0.40570457,
          0.76615147, 0.87762026],
         [0.77705245, 0.30324512, 0.82572333, ..., 0.86971722,
          0.94791273, 0.97971154],
         [0.94476105, 0.35296238, 0.64230563, ..., 0.32146166,
          0.64298044, 0.70922193],
         ...,
         [0.37866132, 0.89883257, 0.81659388, ..., 0.48658337,
          0.35301993, 0.4647407 ],
         [0.29048323, 0.88751687, 0.94404277, ..., 0.5633095 ,
          0.97339728, 0.95935557],
         [0.60490512, 0.46744521, 0.77779438, ..., 0.87693118,
          0.7968958 , 0.64699599]],

        [[0.93605555, 0.29512989, 0.89324983, ..., 0.40570457,
          0.59020046, 0.65082296],
         [0.97193506, 0.16301432, 0.82572333, ..., 0.86971722,
          0.56137604, 0.88470776],
         [0.77089216, 0.48635193, 0.84649126, ..., 0.32146166,
          0.73234106, 0.70922193],
         ...,
         [0.63556955, 0.89883257, 0.81659388, ..., 0.33015303,
          0.17319658, 0.0

In [19]:
z = np.dot(x, y)

In [41]:
x = np.array([1, 2, 3, 4])
y = np.array([2, 22, 1, 3])

In [42]:
def naive_vector_dot(x, y):
    assert len(x.shape) == 1
    assert len(y.shape) == 1
    assert x.shape[0] == y.shape[0]
    z=0.
    for i in range(x.shape[0]):
        z += x[i] * y[i]
    return z

In [43]:
naive_vector_dot(x, y)

61.0

In [44]:
def naive_matrix_vector(x, y):
    assert len(x.shape) == 2
    assert len(y.shape) == 1
    assert x.shape[1] == y.shape[0]
    
    z = np.zeros(x.shape[0])
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            z[i] += x[i, j] * y[j]
    return z

In [46]:
naive_matrix_vector(x, y)

array([782., 817., 822.])

In [70]:
def naive_matrix_dot(x, y):
    assert len(x.shape) == 2
    assert len(y.shape) == 2
    assert x.shape[1] == y.shape[0]
    
    z = np.zeros((x.shape[0], y.shape[1]))
    for i in range(x.shape[0]):
        for j in range(y.shape[1]):
            row_x = x[i, :]
            column_y = y[:, j]
            z[i, j] = naive_vector_dot(row_x, column_y)
    return z

In [71]:
naive_matrix_dot(a, x)

array([[ 483.,  296.,  244., 2836.],
       [  77., 2728.,   90., 1402.],
       [ 262.,  759.,  139., 1579.],
       [ 346., 7984.,  296., 3816.]])

In [52]:
x.shape

(3, 4)

In [55]:
a = a.reshape(4, 3)