In [106]:
import pandas as pd
import numpy as np
import re
import pandas_profiling

ModuleNotFoundError: No module named 'pandas_profiling'

In [2]:
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))
print(weights.tolist())
print(fruit.tolist())

[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
['banana', 'banana', 'apple', 'banana', 'banana', 'carrot', 'apple', 'banana', 'apple', 'apple']


In [3]:
weights.groupby(fruit).mean()

apple     7.25
banana    4.00
carrot    6.00
dtype: float64

In [4]:
p = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
q = pd.Series([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])

In [5]:
sum((p-q)**2)**0.5

18.16590212458495

In [6]:
np.linalg.norm(p - q)

18.16590212458495

In [7]:
ser = pd.Series([2, 10, 3, 4, 9, 10, 2, 7, 3])

In [8]:
from scipy.signal import argrelextrema

In [10]:
ger = np.array(ser)

In [11]:
argrelextrema(ger, np.greater) #first solution, need to convert pandas series to numpy array

(array([1, 5, 7]),)

In [12]:
dd = np.diff(np.sign(np.diff(ser)))

In [14]:
peak_locs = np.where(dd == -2)[0] + 1

In [15]:
peak_locs #second solution

array([1, 5, 7])

In [16]:
my_str = 'dbc deb abed gade'

In [21]:
pattern = re.compile(r"\s")
result = pattern.sub("c", my_str)  # first quicker and smartest solution for replace something in text

In [22]:
result

'dbccdebcabedcgade'

In [23]:
ser = pd.Series(list('dbc deb abed gade'))
freq = ser.value_counts()
print(freq)
least_freq = freq.dropna().index[-1]  # Second dumbiest solution to replace something in text
"".join(ser.replace(' ', least_freq))

d    4
e    3
b    3
     3
a    2
g    1
c    1
dtype: int64


'dbccdebcabedcgade'

In [32]:
dt_df = pd.Series(np.random.randn(10),
                 index=pd.date_range(start='2000-01-01', periods=10, freq='W-SAT'))

In [33]:
dt_df

2000-01-01    0.482921
2000-01-08   -0.042220
2000-01-15    1.184490
2000-01-22   -1.509384
2000-01-29    1.346062
2000-02-05    0.842339
2000-02-12    0.626695
2000-02-19    0.827601
2000-02-26   -0.230845
2000-03-04   -0.191388
Freq: W-SAT, dtype: float64

In [34]:
ser = pd.Series([1,10,3,np.nan], index=pd.to_datetime(['2000-01-01', '2000-01-03', '2000-01-06', '2000-01-08']))


2000-01-01     1.0
2000-01-03    10.0
2000-01-06     3.0
2000-01-08     NaN
dtype: float64


In [44]:
ser.resample('D').ffill() # fill with previous value

2000-01-01     1.0
2000-01-02     1.0
2000-01-03    10.0
2000-01-04    10.0
2000-01-05    10.0
2000-01-06     3.0
2000-01-07     3.0
2000-01-08     NaN
Freq: D, dtype: float64

In [45]:
ser.resample('D').bfill() #fill with next value

2000-01-01     1.0
2000-01-02    10.0
2000-01-03    10.0
2000-01-04     3.0
2000-01-05     3.0
2000-01-06     3.0
2000-01-07     NaN
2000-01-08     NaN
Freq: D, dtype: float64

In [46]:
ser.resample('D').bfill().ffill() #fill next else prev value

2000-01-01     1.0
2000-01-02    10.0
2000-01-03    10.0
2000-01-04     3.0
2000-01-05     3.0
2000-01-06     3.0
2000-01-07     3.0
2000-01-08     3.0
Freq: D, dtype: float64

In [3]:
ser = pd.Series(np.arange(20) + np.random.normal(1, 10, 20))

In [19]:
autocorrelations = [ser.autocorr(i).round(2) for i in range(11)]
print(autocorrelations[1:])
print('Lag having highest correlation: ', np.argmax(np.abs(autocorrelations[1:]))+1)

[0.28, -0.04, -0.12, 0.22, 0.26, 0.45, 0.37, -0.31, -0.07, 0.09]
Lag having highest correlation:  6


In [29]:
[ser.autocorr(i) for i in range(11)] # square bracket!!!

[1.0,
 0.284639404793894,
 -0.03861528609224419,
 -0.116898333569629,
 0.21944995963879035,
 0.25682646857403174,
 0.4472138258109075,
 0.3651972523746804,
 -0.30782659566811804,
 -0.06551230209686507,
 0.09206604034152475]

In [48]:
df = pd.read_csv('/users/karolkul/desktop/code/BostonHousing.csv', chunksize=50)

In [46]:
df2 = pd.DataFrame()
for chunk in df:
    df2 = df2.append(chunk.iloc[0,:]) #Solution 1: Use chunks and for-loop

In [47]:
df2 

age       b  chas      crim     dis  indus  lstat  medv    nox  \
0     65.2  396.90   0.0   0.00632  4.0900   2.31   4.98  24.0  0.538   
50    45.7  395.56   0.0   0.08873  6.8147   5.64  13.45  19.7  0.439   
100   79.9  394.76   0.0   0.14866  2.7778   8.56   9.42  27.5  0.520   
150   97.3  372.80   0.0   1.65660  1.6180  19.58  14.10  21.5  0.871   
200   13.9  384.30   0.0   0.01778  7.6534   1.47   4.45  32.9  0.403   
250   13.0  396.28   0.0   0.14030  7.3967   5.86   5.90  24.4  0.431   
300   47.4  390.86   0.0   0.04417  7.8278   2.24   6.07  24.8  0.400   
350   44.4  396.90   0.0   0.06211  8.7921   1.25   5.98  22.9  0.429   
400  100.0  396.90   0.0  25.04610  1.5888  18.10  26.77   5.6  0.693   
450   92.6    0.32   0.0   6.71772  2.3236  18.10  17.44  13.4  0.713   
500   79.7  396.90   0.0   0.22438  2.4982   9.69  14.33  16.8  0.585   

     ptratio   rad     rm    tax    zn  
0       15.3   1.0  6.575  296.0  18.0  
50      16.8   4.0  5.963  243.0  21.0  
100     20.9   5.0  6.727  384.0   0.0  
150     14.7   5.0  6.122  403.0   0.0  
200     17.0   3.0  7.135  402.0  95.0  
250     19.1   7.0  6.487  330.0  22.0  
300     14.8   5.0  6.871  358.0  70.0  
350     19.7   1.0  6.490  335.0  40.0  
400     20.2  24.0  5.987  666.0   0.0  
450     20.2  24.0  6.749  666.0   0.0  
500     19.2   6.0  6.027  391.0   0.0

In [49]:
df = pd.read_csv('/users/karolkul/desktop/code/BostonHousing.csv', chunksize=50)

In [50]:
df2 = pd.concat([chunk.iloc[0] for chunk in df], axis=1)
df2 = df2.transpose()    #Solution 2: Use chunks and list comprehension

In [51]:
df2

crim    zn  indus  chas    nox     rm    age     dis   rad    tax  \
0     0.00632  18.0   2.31   0.0  0.538  6.575   65.2  4.0900   1.0  296.0   
50    0.08873  21.0   5.64   0.0  0.439  5.963   45.7  6.8147   4.0  243.0   
100   0.14866   0.0   8.56   0.0  0.520  6.727   79.9  2.7778   5.0  384.0   
150   1.65660   0.0  19.58   0.0  0.871  6.122   97.3  1.6180   5.0  403.0   
200   0.01778  95.0   1.47   0.0  0.403  7.135   13.9  7.6534   3.0  402.0   
250   0.14030  22.0   5.86   0.0  0.431  6.487   13.0  7.3967   7.0  330.0   
300   0.04417  70.0   2.24   0.0  0.400  6.871   47.4  7.8278   5.0  358.0   
350   0.06211  40.0   1.25   0.0  0.429  6.490   44.4  8.7921   1.0  335.0   
400  25.04610   0.0  18.10   0.0  0.693  5.987  100.0  1.5888  24.0  666.0   
450   6.71772   0.0  18.10   0.0  0.713  6.749   92.6  2.3236  24.0  666.0   
500   0.22438   0.0   9.69   0.0  0.585  6.027   79.7  2.4982   6.0  391.0   

     ptratio       b  lstat  medv  
0       15.3  396.90   4.98  24.0  
50      16.8  395.56  13.45  19.7  
100     20.9  394.76   9.42  27.5  
150     14.7  372.80  14.10  21.5  
200     17.0  384.30   4.45  32.9  
250     19.1  396.28   5.90  24.4  
300     14.8  390.86   6.07  24.8  
350     19.7  396.90   5.98  22.9  
400     20.2  396.90  26.77   5.6  
450     20.2    0.32  17.44  13.4  
500     19.2  396.90  14.33  16.8

In [52]:
import csv

In [56]:
with open('/users/karolkul/desktop/code/BostonHousing.csv', 'r') as f:
    reader = csv.reader(f)
    out = []
    for i, row in enumerate(reader):          #Solution 3: Use csv reader
        if i%50 == 0:
            out.append(row)

In [58]:
df2 = pd.DataFrame(out[1:], columns=out[0])
print(df2.head())

      crim  zn  indus chas    nox     rm   age     dis rad  tax ptratio  \
0  0.21977   0   6.91    0  0.448  5.602    62  6.0877   3  233    17.9   
1   0.0686   0   2.89    0  0.445  7.416  62.5  3.4952   2  276      18   
2  2.73397   0  19.58    0  0.871  5.597  94.9  1.5257   5  403    14.7   
3   0.0315  95   1.47    0  0.403  6.975  15.3  7.6534   3  402      17   
4  0.19073  22   5.86    0  0.431  6.718  17.5  7.8265   7  330    19.1   

        b  lstat  medv  
0   396.9   16.2  19.4  
1   396.9   6.19  33.2  
2  351.85  21.45  15.4  
3   396.9   4.56  34.9  
4  393.74   6.56  26.2  


In [77]:
df = pd.read_csv('/users/karolkul/desktop/code/BostonHousing.csv',
                converters={'medv': lambda x: 'Low' if float(x) < 25 else 'High'})

In [78]:
df

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273   

     ptratio       b  lstat  medv  
0       15.3  396.90   4.98   Low  
1       17.8  396.90   9.14   Low  
2       17.8  392.83   4.03  High  
3       18.7  394.63   2.94  High  
4       18.7  396.90   5.33  High  
..       ...     ...    ...   ...  
501     21.0  391.99   9.67   Low  
502     21.0  396.90   9.08   Low  
503     21.0  396.90   5.64   Low  
504     21.0  393.45   6.48   Low  
505     21.0  396.90   7.88   Low  

[506 rows x 14 columns]

In [92]:
L = pd.Series(range(15))

In [93]:
arr = np.asarray(L)

In [94]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [96]:
def gen_strides(a, stride_len=5, window_len=5):
    n_strides = ((a.size-window_len)//stride_len) + 1
    return np.array([a[s:(s+window_len)] for s in np.arange(0, a.size, stride_len)[:n_strides]])

gen_strides(L, stride_len=2, window_len=4)

array([[ 0,  1,  2,  3],
       [ 2,  3,  4,  5],
       [ 4,  5,  6,  7],
       [ 6,  7,  8,  9],
       [ 8,  9, 10, 11],
       [10, 11, 12, 13]])

In [99]:
df = pd.read_csv('/users/karolkul/desktop/code/BostonHousing.csv', usecols=['crim','medv'])

In [100]:
df

crim  medv
0    0.00632  24.0
1    0.02731  21.6
2    0.02729  34.7
3    0.03237  33.4
4    0.06905  36.2
..       ...   ...
501  0.06263  22.4
502  0.04527  20.6
503  0.06076  23.9
504  0.10959  22.0
505  0.04741  11.9

[506 rows x 2 columns]

In [101]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [103]:
df

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small       12.9   15.9       18.8      25.0   
1           NaN   Legend  Midsize       29.2   33.9       38.7      18.0   
2          Audi       90  Compact       25.9   29.1       32.3      20.0   
3          Audi      100  Midsize        NaN   37.7       44.6      19.0   
4           BMW     535i  Midsize        NaN   30.0        NaN      22.0   
..          ...      ...      ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan      Van       16.6   19.7       22.7      17.0   
89   Volkswagen   Passat  Compact       17.6   20.0       22.4      21.0   
90   Volkswagen  Corrado   Sporty       22.9   23.3       23.7      18.0   
91        Volvo      240  Compact       21.8   22.7       23.5      21.0   
92          NaN      850  Midsize       24.8   26.7       28.5      20.0   

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31.0                None      Front  ...        5.0   177.0   
1          25.0  Driver & Passenger      Front  ...        5.0   195.0   
2          26.0         Driver only      Front  ...        5.0   180.0   
3          26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4          30.0                 NaN       Rear  ...        4.0   186.0   
..          ...                 ...        ...  ...        ...     ...   
88         21.0                None      Front  ...        7.0   187.0   
89         30.0                None      Front  ...        5.0   180.0   
90         25.0                None      Front  ...        4.0   159.0   
91         28.0         Driver only       Rear  ...        5.0   190.0   
92         28.0  Driver & Passenger      Front  ...        5.0   184.0   

    Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0       102.0   68.0         37.0           26.5           NaN  2705.0   
1       115.0   71.0         38.0           30.0          15.0  3560.0   
2       102.0   67.0         37.0           28.0          14.0  3375.0   
3       106.0    NaN         37.0           31.0          17.0  3405.0   
4       109.0   69.0         39.0           27.0          13.0  3640.0   
..        ...    ...          ...            ...           ...     ...   
88      115.0   72.0         38.0           34.0           NaN  3960.0   
89      103.0   67.0         35.0           31.5          14.0  2985.0   
90       97.0   66.0         36.0           26.0          15.0  2810.0   
91      104.0   67.0         37.0           29.5          14.0  2985.0   
92      105.0   69.0         38.0           30.0          15.0  3245.0   

     Origin                Make  
0   non-USA       Acura Integra  
1   non-USA        Acura Legend  
2   non-USA             Audi 90  
3   non-USA            Audi 100  
4   non-USA            BMW 535i  
..      ...                 ...  
88      NaN  Volkswagen Eurovan  
89  non-USA   Volkswagen Passat  
90  non-USA  Volkswagen Corrado  
91  non-USA           Volvo 240  
92  non-USA           Volvo 850  

[93 rows x 27 columns]

In [117]:
print('Count of columns: ',len(df.columns), 'Count of rows: ',len(df.index),'Datatype: ', df.dtypes)

Count of columns:  27 Count of rows:  93 Datatype:  Manufacturer           object
Model                  object
Type                   object
Min.Price             float64
Price                 float64
Max.Price             float64
MPG.city              float64
MPG.highway           float64
AirBags                object
DriveTrain             object
Cylinders              object
EngineSize            float64
Horsepower            float64
RPM                   float64
Rev.per.mile          float64
Man.trans.avail        object
Fuel.tank.capacity    float64
Passengers            float64
Length                float64
Wheelbase             float64
Width                 float64
Turn.circle           float64
Rear.seat.room        float64
Luggage.room          float64
Weight                float64
Origin                 object
Make                   object
dtype: object


In [120]:
print(df.dtypes.value_counts())

float64    18
object      9
dtype: int64


In [122]:
df_stats = df.describe()

In [123]:
df_stats

Min.Price      Price  Max.Price   MPG.city  MPG.highway  EngineSize  \
count  86.000000  91.000000  88.000000  84.000000    91.000000   91.000000   
mean   17.118605  19.616484  21.459091  22.404762    29.065934    2.658242   
std     8.828290   9.724280  10.696563   5.841520     5.370293    1.045845   
min     6.700000   7.400000   7.900000  15.000000    20.000000    1.000000   
25%    10.825000  12.350000  14.575000  18.000000    26.000000    1.800000   
50%    14.600000  17.700000  19.150000  21.000000    28.000000    2.300000   
75%    20.250000  23.500000  24.825000  25.000000    31.000000    3.250000   
max    45.400000  61.900000  80.000000  46.000000    50.000000    5.700000   

       Horsepower          RPM  Rev.per.mile  Fuel.tank.capacity  Passengers  \
count   86.000000    90.000000     87.000000           85.000000   91.000000   
mean   144.000000  5276.666667   2355.000000           16.683529    5.076923   
std     53.455204   605.554811    486.916616            3.375748    1.045953   
min     55.000000  3800.000000   1320.000000            9.200000    2.000000   
25%    100.750000  4800.000000   2017.500000           14.500000    4.000000   
50%    140.000000  5200.000000   2360.000000           16.500000    5.000000   
75%    170.000000  5787.500000   2565.000000           19.000000    6.000000   
max    300.000000  6500.000000   3755.000000           27.000000    8.000000   

           Length   Wheelbase      Width  Turn.circle  Rear.seat.room  \
count   89.000000   92.000000  87.000000    88.000000       89.000000   
mean   182.865169  103.956522  69.448276    38.954545       27.853933   
std     14.792651    6.856317   3.778023     3.304157        3.018129   
min    141.000000   90.000000  60.000000    32.000000       19.000000   
25%    174.000000   98.000000  67.000000    36.000000       26.000000   
50%    181.000000  103.000000  69.000000    39.000000       27.500000   
75%    192.000000  110.000000  72.000000    42.000000       30.000000   
max    219.000000  119.000000  78.000000    45.000000       36.000000   

       Luggage.room       Weight  
count     74.000000    86.000000  
mean      13.986486  3104.593023  
std        3.120824   600.129993  
min        6.000000  1695.000000  
25%       12.000000  2647.500000  
50%       14.000000  3085.000000  
75%       16.000000  3567.500000  
max       22.000000  4105.000000

In [124]:
df_arr = df.values

In [125]:
df_arr

array([['Acura', 'Integra', 'Small', ..., 2705.0, 'non-USA',
        'Acura Integra'],
       [nan, 'Legend', 'Midsize', ..., 3560.0, 'non-USA', 'Acura Legend'],
       ['Audi', '90', 'Compact', ..., 3375.0, 'non-USA', 'Audi 90'],
       ...,
       ['Volkswagen', 'Corrado', 'Sporty', ..., 2810.0, 'non-USA',
        'Volkswagen Corrado'],
       ['Volvo', '240', 'Compact', ..., 2985.0, 'non-USA', 'Volvo 240'],
       [nan, '850', 'Midsize', ..., 3245.0, 'non-USA', 'Volvo 850']],
      dtype=object)

In [127]:
df_list = df.values.tolist()

In [128]:
df_list

[['Acura',
  'Integra',
  'Small',
  12.9,
  15.9,
  18.8,
  25.0,
  31.0,
  'None',
  'Front',
  '4',
  1.8,
  140.0,
  6300.0,
  2890.0,
  'Yes',
  13.2,
  5.0,
  177.0,
  102.0,
  68.0,
  37.0,
  26.5,
  nan,
  2705.0,
  'non-USA',
  'Acura Integra'],
 [nan,
  'Legend',
  'Midsize',
  29.2,
  33.9,
  38.7,
  18.0,
  25.0,
  'Driver & Passenger',
  'Front',
  '6',
  3.2,
  200.0,
  5500.0,
  2335.0,
  'Yes',
  18.0,
  5.0,
  195.0,
  115.0,
  71.0,
  38.0,
  30.0,
  15.0,
  3560.0,
  'non-USA',
  'Acura Legend'],
 ['Audi',
  '90',
  'Compact',
  25.9,
  29.1,
  32.3,
  20.0,
  26.0,
  'Driver only',
  'Front',
  '6',
  2.8,
  172.0,
  5500.0,
  2280.0,
  'Yes',
  16.9,
  5.0,
  180.0,
  102.0,
  67.0,
  37.0,
  28.0,
  14.0,
  3375.0,
  'non-USA',
  'Audi 90'],
 ['Audi',
  '100',
  'Midsize',
  nan,
  37.7,
  44.6,
  19.0,
  26.0,
  'Driver & Passenger',
  nan,
  '6',
  nan,
  172.0,
  5500.0,
  2535.0,
  nan,
  21.1,
  6.0,
  193.0,
  106.0,
  nan,
  37.0,
  31.0,
  17.0,
  3405.0,
