In [2]:
import pandas as pd
import numpy as np
from scipy import stats

In [3]:
df = pd.DataFrame(np.random.random(4), columns=['random'])

In [8]:
df.style.format("{:.2%}")

In [9]:
out = df.style.format({
    'random': '{0:.2%}'.format,
})

In [53]:
out

In [26]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [20]:
df.iloc[::20,:][['Manufacturer', 'Model', 'Type']]

Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small

In [32]:
df[['Manufacturer', 'Model', 'Type']] = df[['Manufacturer', 'Model', 'Type']].fillna('missing')

In [47]:
df = df.set_index(index)

In [42]:
index = [df['Manufacturer'] + ['_'] + df['Model']+ ['_'] + df['Type']]

In [48]:
df

Manufacturer    Model     Type  Min.Price  Price  \
Acura_Integra_Small              Acura  Integra    Small       12.9   15.9   
missing_Legend_Midsize         missing   Legend  Midsize       29.2   33.9   
Audi_90_Compact                   Audi       90  Compact       25.9   29.1   
Audi_100_Midsize                  Audi      100  Midsize        NaN   37.7   
BMW_535i_Midsize                   BMW     535i  Midsize        NaN   30.0   
...                                ...      ...      ...        ...    ...   
Volkswagen_Eurovan_Van      Volkswagen  Eurovan      Van       16.6   19.7   
Volkswagen_Passat_Compact   Volkswagen   Passat  Compact       17.6   20.0   
Volkswagen_Corrado_Sporty   Volkswagen  Corrado   Sporty       22.9   23.3   
Volvo_240_Compact                Volvo      240  Compact       21.8   22.7   
missing_850_Midsize            missing      850  Midsize       24.8   26.7   

                           Max.Price  MPG.city  MPG.highway  \
Acura_Integra_Small             18.8      25.0         31.0   
missing_Legend_Midsize          38.7      18.0         25.0   
Audi_90_Compact                 32.3      20.0         26.0   
Audi_100_Midsize                44.6      19.0         26.0   
BMW_535i_Midsize                 NaN      22.0         30.0   
...                              ...       ...          ...   
Volkswagen_Eurovan_Van          22.7      17.0         21.0   
Volkswagen_Passat_Compact       22.4      21.0         30.0   
Volkswagen_Corrado_Sporty       23.7      18.0         25.0   
Volvo_240_Compact               23.5      21.0         28.0   
missing_850_Midsize             28.5      20.0         28.0   

                                      AirBags DriveTrain  ... Passengers  \
Acura_Integra_Small                      None      Front  ...        5.0   
missing_Legend_Midsize     Driver & Passenger      Front  ...        5.0   
Audi_90_Compact                   Driver only      Front  ...        5.0   
Audi_100_Midsize           Driver & Passenger        NaN  ...        6.0   
BMW_535i_Midsize                          NaN       Rear  ...        4.0   
...                                       ...        ...  ...        ...   
Volkswagen_Eurovan_Van                   None      Front  ...        7.0   
Volkswagen_Passat_Compact                None      Front  ...        5.0   
Volkswagen_Corrado_Sporty                None      Front  ...        4.0   
Volvo_240_Compact                 Driver only       Rear  ...        5.0   
missing_850_Midsize        Driver & Passenger      Front  ...        5.0   

                           Length  Wheelbase  Width  Turn.circle  \
Acura_Integra_Small         177.0      102.0   68.0         37.0   
missing_Legend_Midsize      195.0      115.0   71.0         38.0   
Audi_90_Compact             180.0      102.0   67.0         37.0   
Audi_100_Midsize            193.0      106.0    NaN         37.0   
BMW_535i_Midsize            186.0      109.0   69.0         39.0   
...                           ...        ...    ...          ...   
Volkswagen_Eurovan_Van      187.0      115.0   72.0         38.0   
Volkswagen_Passat_Compact   180.0      103.0   67.0         35.0   
Volkswagen_Corrado_Sporty   159.0       97.0   66.0         36.0   
Volvo_240_Compact           190.0      104.0   67.0         37.0   
missing_850_Midsize         184.0      105.0   69.0         38.0   

                          Rear.seat.room  Luggage.room  Weight   Origin  \
Acura_Integra_Small                 26.5           NaN  2705.0  non-USA   
missing_Legend_Midsize              30.0          15.0  3560.0  non-USA   
Audi_90_Compact                     28.0          14.0  3375.0  non-USA   
Audi_100_Midsize                    31.0          17.0  3405.0  non-USA   
BMW_535i_Midsize                    27.0          13.0  3640.0  non-USA   
...                                  ...           ...     ...      ...   
Volkswagen_Eurovan_Van              34.0           NaN  3960.0      NaN   
Vo

In [55]:
df.loc['Audi_90_Compact']

Manufacturer                 Audi
Model                          90
Type                      Compact
Min.Price                    25.9
Price                        29.1
Max.Price                    32.3
MPG.city                       20
MPG.highway                    26
AirBags               Driver only
DriveTrain                  Front
Cylinders                       6
EngineSize                    2.8
Horsepower                    172
RPM                          5500
Rev.per.mile                 2280
Man.trans.avail               Yes
Fuel.tank.capacity           16.9
Passengers                      5
Length                        180
Wheelbase                     102
Width                          67
Turn.circle                    37
Rear.seat.room                 28
Luggage.room                   14
Weight                       3375
Origin                    non-USA
Make                      Audi 90
Name: Audi_90_Compact, dtype: object

In [72]:
df = pd.DataFrame(np.random.randint(1, 30, 30).reshape(10,-1), columns=list('abc'))

In [77]:
grouped_df = df.groupby("a")

In [78]:
max_value = grouped_df.max()

In [79]:
max_value = max_value.reset_index()

In [85]:
max_value['a'].iloc[5]

21

In [94]:
fifth_value = np.where(df['a'].values == 21)

In [95]:
fifth_value

(array([9]),)

In [96]:
df

a   b   c
0   8  26   4
1  13  22   6
2   6  22   6
3  25   5  13
4   8   7   4
5  23  24   5
6   5  24  28
7  20   4   4
8  27  12  27
9  21  26   9

In [98]:
n = 6
df['a'].argsort()[::-1][n]

9

In [99]:
df['b'][::-1][1]

22

In [123]:
ser = pd.Series(np.random.randint(1, 100, 15))

In [124]:
print('ser: ', ser.tolist(), 'mean: ', round(ser.mean()))

ser:  [42, 15, 93, 68, 64, 27, 31, 75, 67, 50, 60, 77, 75, 62, 22] mean:  55.0


In [155]:
np.where(ser > ser.mean())

(array([ 2,  3,  4,  7,  8, 10, 11, 12, 13]),)

In [146]:
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

In [147]:
df['sum'] = df.sum(axis=1)

In [148]:
df

0   1   2   3  sum
0   26  34  29  34  123
1   14  15  20  16   65
2   26  33  36  16  111
3   23  15  32  38  108
4   31  30  27  38  126
5   14  20  36  31  101
6   11  18  24  15   68
7   35  17  30  24  106
8   16  37  13  20   86
9   36  28  13  35  112
10  24  24  11  19   78
11  28  34  38  37  137
12  23  25  17  31   96
13  38  14  28  18   98
14  35  14  15  37  101

In [162]:
np.where(df['sum'] > 100)[0][-2:]

array([11, 14])

In [160]:
s[-2:]

array([11, 14])

In [164]:
# another way to do that/using numpy
rowsums = df.apply(np.sum, axis=1)
rowsums

0     246
1     130
2     222
3     216
4     252
5     202
6     136
7     212
8     172
9     224
10    156
11    274
12    192
13    196
14    202
dtype: int64

In [167]:
last_two_rows = df.iloc[np.where(rowsums > 200)[0][-2:], :]
last_two_rows

0   1   2   3  sum
11  28  34  38  37  137
14  35  14  15  37  101

In [170]:
ser = pd.Series(np.logspace(-2, 2, 30))

In [178]:
ser

0       0.010000
1       0.013738
2       0.018874
3       0.025929
4       0.035622
5       0.048939
6       0.067234
7       0.092367
8       0.126896
9       0.174333
10      0.239503
11      0.329034
12      0.452035
13      0.621017
14      0.853168
15      1.172102
16      1.610262
17      2.212216
18      3.039195
19      4.175319
20      5.736153
21      7.880463
22     10.826367
23     14.873521
24     20.433597
25     28.072162
26     38.566204
27     52.983169
28     72.789538
29    100.000000
dtype: float64

In [174]:
z = np.abs(stats.zscore(ser))

In [175]:
z

array([0.51770392, 0.5175458 , 0.51732857, 0.51703013, 0.51662013,
       0.51605686, 0.51528303, 0.51421992, 0.51275939, 0.51075289,
       0.5079963 , 0.50420924, 0.49900649, 0.49185882, 0.48203919,
       0.46854874, 0.45001524, 0.42455348, 0.38957351, 0.3415172 ,
       0.27549628, 0.18479518, 0.06018785, 0.11100066, 0.34618352,
       0.66928332, 1.11316551, 1.72298144, 2.56076107, 3.71172265])

In [176]:
threshold = 3

In [196]:
print(np.where(z > 3))

(array([29]),)


In [183]:
q1 = ser.quantile(0.05)
q2 = ser.quantile(0.95)

In [197]:
q1, q2

(0.016049294076965887, 63.876672220183934)

In [188]:
# doesnt work, why?
ser.replace([[ser.values < q1], [ser.values > q2]])

0       0.010000
1       0.013738
2       0.018874
3       0.025929
4       0.035622
5       0.048939
6       0.067234
7       0.092367
8       0.126896
9       0.174333
10      0.239503
11      0.329034
12      0.452035
13      0.621017
14      0.853168
15      1.172102
16      1.610262
17      2.212216
18      3.039195
19      4.175319
20      5.736153
21      7.880463
22     10.826367
23     14.873521
24     20.433597
25     28.072162
26     38.566204
27     52.983169
28     72.789538
29    100.000000
dtype: float64

In [189]:
def cap_outliers(ser, low_perc, high_perc):
    low, high = ser.quantile([low_perc, high_perc])
    print(low_perc, '%ile: ', low, '|', high_perc, '%ile: ', high)
    ser[ser < low] = low
    ser[ser > high] = high
    return(ser)

In [191]:
capped_ser = cap_outliers(ser, .05, .95)

0.05 %ile:  0.016049294076965887 | 0.95 %ile:  63.876672220183934


In [198]:
df = pd.DataFrame(np.random.randint(-20, 50, 100).reshape(10,-1))

In [204]:
arr = df.to_numpy()

In [225]:
new_arr = np.delete(arr, np.where(arr < 0)) 
# Delte only 10 value. why?

In [235]:
new_arr.reshape(9, 10)

array([[ 35,  -7,  24, -20,  48,  -5,  12,  30,  28,  20],
       [ 39,  14,   2,   9,  11,  41,   3,  12,  16,  12],
       [ 22,  44,  -2, -18,  25,  17,  41,  11,  11,  31],
       [ -9,  23,  48, -14,  29,  36,  40,  28,  -8, -17],
       [ 36,  18,  34,   7,  43,   6,  18,  45,  -5,  46],
       [  7,   1,   5,  38,  35,  40,  38,   9,  -7,  19],
       [ 30,  45,  28,  19,  38, -17,  30,  18,  -3,  11],
       [ 31,  -7, -11,  18,  31,  19, -10,  31, -20,   8],
       [  5,  25,  31,  39,  -5,  13,   5,  49,   4,  13]])

In [240]:
# Remove negative values from arr
arr = df[df > 0].values.flatten()

In [241]:
arr_qualified = arr[~np.isnan(arr)]

In [244]:
# Find side-length of largest possible square
n = int(np.floor(arr_qualified.shape[0]**.5))

In [246]:
# Take top n^2 items without changing positions
top_indexes = np.argsort(arr_qualified)[::-1]

In [251]:
output = np.take(arr_qualified, sorted(top_indexes[:n**2])).reshape(n, -1)

In [252]:
output

array([[29., 14., 34., 32., 39., 16., 35., 24.],
       [48., 12., 30., 28., 20., 39., 14., 11.],
       [41., 12., 16., 12., 22., 44., 25., 17.],
       [41., 11., 31., 23., 48., 29., 36., 40.],
       [28., 36., 18., 34., 43., 18., 45., 46.],
       [38., 35., 40., 38., 19., 30., 45., 28.],
       [19., 38., 30., 18., 11., 31., 18., 31.],
       [19., 31., 25., 31., 39., 13., 49., 13.]])

In [292]:
df = pd.DataFrame(np.arange(25).reshape(5, -1))

In [272]:
df.replace(df.iloc[1], df.iloc[2])

0   1   2   3   4
0  10  11  12  13  14
1  10  11  12  13  14
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

In [293]:
arr = df.to_numpy()

In [294]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [295]:
arr[[1, 2]] = arr[[2, 1]]

In [296]:
arr

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [297]:
# Second way to do this, FUNCTION
def swap_rows(df, i1, i2):
    a, b = df.iloc[i1, :].copy(), df.iloc[i2, :].copy()
    df.iloc[i1, :], df.iloc[i2, :] = b, a
    return df

In [300]:
swap_rows(df, 1, 2)

0   1   2   3   4
0   0   1   2   3   4
1  10  11  12  13  14
2   5   6   7   8   9
3  15  16  17  18  19
4  20  21  22  23  24

In [299]:
df

0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

In [3]:
ser = pd.Series(np.random.randint(1, 100, 15))

In [18]:
ser.get(ser.mean() < ser).sort_values().tolist()[1]

56

In [20]:
df = pd.DataFrame(np.arange(25).reshape(5, -1))

In [32]:
df.iloc[::-1, :]

0   1   2   3   4
4  20  21  22  23  24
3  15  16  17  18  19
2  10  11  12  13  14
1   5   6   7   8   9
0   0   1   2   3   4

In [33]:
df.reindex(index=df.index[::-1])

0   1   2   3   4
4  20  21  22  23  24
3  15  16  17  18  19
2  10  11  12  13  14
1   5   6   7   8   9
0   0   1   2   3   4

In [42]:
df = pd.DataFrame(np.arange(25).reshape(5,-1), columns=list('abcde'))

In [50]:
df1 = pd.get_dummies(df['a'])

In [55]:
df1.join(df.iloc[0:5, 1:5])

0  5  10  15  20   b   c   d   e
0  1  0   0   0   0   1   2   3   4
1  0  1   0   0   0   6   7   8   9
2  0  0   1   0   0  11  12  13  14
3  0  0   0   1   0  16  17  18  19
4  0  0   0   0   1  21  22  23  24

In [56]:
df_onehot = pd.concat([pd.get_dummies(df['a']), df[list('bcde')]], axis=1)
df_onehot

0  5  10  15  20   b   c   d   e
0  1  0   0   0   0   1   2   3   4
1  0  1   0   0   0   6   7   8   9
2  0  0   1   0   0  11  12  13  14
3  0  0   0   1   0  16  17  18  19
4  0  0   0   0   1  21  22  23  24

In [57]:
df = pd.DataFrame(np.random.randint(1,100, 40).reshape(10, -1))

In [78]:
df.max(axis=1).sort_values(ascending=False)

9    99
0    96
8    94
3    94
2    94
5    90
7    87
6    85
1    83
4    78
dtype: int64

In [68]:
df

0   1   2   3
0  81  94  22  96
1  83  64  41  41
2  64  94  32  82
3  66  94  94  75
4  30   4  78   4
5  90  71  73  43
6  36  85  25  14
7   5  87  35  44
8  62  94  39  21
9  45   9  99   6

In [84]:
df.apply(np.argmax, axis=1).value_counts().index[0]

1

In [120]:
df = pd.DataFrame(np.random.randint(1,100, 40).reshape(10, -1), columns=list('pqrs'), index=list('abcdefghij'))

In [121]:
df

p   q   r   s
a  26  59  84  35
b  19  68  45  74
c  67  99  58  33
d  86  20  33  33
e  73  73  37  65
f  68  69  68  62
g  96  43  41  99
h  61  82  27  32
i  71  60  87  46
j   2  66  29   2

In [122]:
nearest_rows = []  #!!!!!!!!!!
nearest_distance = []  #!!!!!!!!!!!!!!

In [123]:
for i, row in df.iterrows():
    curr = row
    rest = df.drop(i)
    e_dists = {} # init dict to store euclidean dists for current row.
    # iterate rest of rows for current row
    for j, contestant in rest.iterrows():
        # compute euclidean dist nad update e_dists
        e_dists.update({j: round(np.linalg.norm(curr.values - contestant.values))})
    # update nearest row to current row and the distance
    nearest_rows.append(max(e_dists, key=e_dists.get))
    nearest_distance.append(max(e_dists.values()))
    
df['nearest_row'] = nearest_rows
df['dist'] = nearest_distance

In [124]:
df

p   q   r   s nearest_row   dist
a  26  59  84  35           g  105.0
b  19  68  45  74           d   93.0
c  67  99  58  33           g   93.0
d  86  20  33  33           j  101.0
e  73  73  37  65           j   96.0
f  68  69  68  62           j   97.0
g  96  43  41  99           j  138.0
h  61  82  27  32           g   86.0
i  71  60  87  46           j  100.0
j   2  66  29   2           g  138.0

In [125]:
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1), columns=list('pqrstuvwxy'), index=list('abcdefgh'))

In [128]:
abscorr = np.abs(df.corr())

In [129]:
max_corr = abscorr.apply(lambda x: sorted(x)[-2])

In [133]:
np.round(max_corr, 2)

p    0.71
q    0.60
r    0.71
s    0.52
t    0.63
u    0.63
v    0.84
w    0.71
x    0.84
y    0.39
dtype: float64

In [131]:
np.round(max_corr.tolist(), 2)

array([0.71, 0.6 , 0.71, 0.52, 0.63, 0.63, 0.84, 0.71, 0.84, 0.39])

In [134]:
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

In [164]:
df['min/max'] = (df.min() / df.max())

In [165]:
np.round(df, 5)

0   1   2   3   4   5   6   7   8   9  min/max
0  99  52  89  16  56  12  29  27  44  16  0.02020
1  71  79  41  87  41  67  51  85  49  71  0.10101
2  41  15  12  83  75  80   9  27  40  81  0.12371
3  92  79  63  43  82  42  90  78  27  25  0.18391
4  13  62  97  21   3  68  92  48  46  10  0.03297
5   4  60  77  27  91  68  98  89  31  63  0.15000
6  95  99  50  80  68  76  47  90  90  98  0.09184
7   2  10  90  69   5  60  93  26  28  72  0.28889

In [203]:
np.min(df.drop(['min/max'], axis=1).loc[1,:]) # ????

41

In [194]:
np.max(df.loc[1,:])

87.0

In [195]:
np.min(df.loc[:,1])

10

In [173]:
ser = pd.Series([1, 2, 3, 4, 5, 6])

In [191]:
np.min(ser)

1

In [158]:
min_by_max = df.apply(lambda x: np.min(x) / np.max(x), axis=1) #???

In [160]:
minbymax = np.min(df, axis=1)/np.max(df, axis=1) #???

In [204]:
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

In [205]:
df

0   1   2   3   4   5   6   7   8   9
0  24  45  87  39  59  55   1  34  26  36
1  48  40  52  41   3  91  16  52  61  81
2  11  46  10  32   8  91  71  40  14  62
3  70  97   3  81  40  43  23  77  64  95
4  36  72  44  87  53  48  96  98  38  90
5  59  24  19  13  28  35  20  44  61  18
6  55  81  55  59  98  77  70  47   1  43
7  26  13  21  72  37  12  13  99  92  79

In [221]:
penultimate = np.sort(df, axis=1)[:, 8]

In [222]:
penultimate

array([59, 81, 71, 95, 96, 59, 81, 92])

In [223]:
df['pen'] = penultimate

In [224]:
df

0   1   2   3   4   5   6   7   8   9  pen
0  24  45  87  39  59  55   1  34  26  36   59
1  48  40  52  41   3  91  16  52  61  81   81
2  11  46  10  32   8  91  71  40  14  62   71
3  70  97   3  81  40  43  23  77  64  95   95
4  36  72  44  87  53  48  96  98  38  90   96
5  59  24  19  13  28  35  20  44  61  18   59
6  55  81  55  59  98  77  70  47   1  43   81
7  26  13  21  72  37  12  13  99  92  79   92

In [225]:
out = df.apply(lambda x: x.sort_values().unique()[-2], axis=1)

In [226]:
out

0    59
1    81
2    71
3    95
4    96
5    59
6    81
7    92
dtype: int64

In [260]:
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

In [233]:
normalize = df.mean() / df.std()

In [236]:
normalize

0    1.541297
1    2.027887
2    2.874640
3    1.488471
4    1.674715
5    2.568579
6    3.078199
7    2.414639
8    1.470135
9    1.694110
dtype: float64

In [253]:
df = df.replace(df.max(), 1)

In [251]:
df = df.replace(df.min(), 0)

In [254]:
df

0   1   2   3   4   5   6   7   8   9
0  73  56   1  45   1  35   1   1  28  64
1  21   1  53   6  17  43  29  56   1   9
2   1  40   0  63  23  38  39  51   8   0
3   0  43  71   1  30   0   0   4  47  31
4  76  11  70  40   1  59  83  63   0  21
5   6  31  53   0  81   1   1  66  28  59
6  31   0  24  48   0  25  73  54  42   1
7  28  45   0   5  35  28   1   0  10  86

In [292]:
out = df.apply(lambda x: ((x - x.mean())/x.std()).round(2))

In [293]:
out

0     1     2     3     4     5     6     7     8     9
0 -0.40 -0.47 -1.16  0.79  0.92  1.85 -0.28  0.16 -1.06  1.35
1 -0.12 -1.18  1.15 -0.67  0.15  0.15  1.00 -0.34  0.82  1.27
2 -1.54  1.24 -0.42 -0.89 -1.30 -1.00  0.71  0.10  0.11 -1.42
3  1.21 -0.69 -0.58  1.38  1.32  1.04  1.06  1.28 -0.35  0.00
4 -0.83 -0.96  0.96 -1.00 -0.12 -1.07 -1.18  1.46 -1.52  0.54
5 -0.37  0.38 -0.58  0.44 -0.79 -0.18 -1.56 -0.24  1.28 -0.96
6  1.21  0.17 -0.77  0.99  0.92 -0.37 -0.34 -0.99 -0.31 -0.38
7  0.84  1.51  1.41 -1.03 -1.10 -0.41  0.58 -1.43  1.03 -0.42

In [294]:
out1 = df.apply(lambda x: ((x.max() - x)/(x.max() - x.min())).round(2))

In [295]:
out1

0     1     2     3     4     5     6     7     8     9
0  0.58  0.74  1.00  0.24  0.15  0.00  0.51  0.45  0.84  0.00
1  0.48  1.00  0.10  0.85  0.45  0.58  0.02  0.62  0.16  0.03
2  1.00  0.10  0.71  0.94  1.00  0.97  0.13  0.47  0.42  1.00
3  0.00  0.82  0.78  0.00  0.00  0.28  0.00  0.06  0.58  0.49
4  0.74  0.92  0.18  0.99  0.55  1.00  0.85  0.00  1.00  0.29
5  0.57  0.42  0.78  0.39  0.81  0.70  1.00  0.59  0.00  0.83
6  0.00  0.50  0.85  0.16  0.15  0.76  0.54  0.85  0.57  0.62
7  0.13  0.00  0.00  1.00  0.92  0.77  0.18  1.00  0.09  0.64

In [296]:
df

0   1   2   3   4   5   6   7   8   9
0  44  25  11  73  84  84  57  56  25  73
1  53   2  83  20  61  38  97  40  78  71
2   7  81  34  12  18   7  88  54  58   1
3  96  18  29  94  96  62  99  92  45  38
4  30   9  77   8  53   5  29  98  12  52
5  45  53  29  60  33  29  17  43  91  13
6  96  46  23  80  84  24  55  19  46  28
7  84  90  91   7  24  23  84   5  84  27

In [301]:
(99 - 44) / (99 - 1)

0.5612244897959183

In [278]:
df.iloc[0, ::].max()

84

In [302]:
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

In [305]:
df

0   1   2   3   4   5   6   7   8   9
0  98  56  56  13  23  20  46  10  82  35
1  37  86  34  56   6  98  32  67  65  71
2  70  34  43  41  70  46  17  45  21  59
3  84  35  79  74  72  24  97  41  90  65
4  90  74  63  26  45   4  12  54  18  64
5  80  91   1  38  58  66  68  58  19  98
6  94  97   7  69  92  13  32  29  23  95
7  52  54  48  63  84  27  99  57  68  77

In [342]:
df.apply(lambda x: ([x.corr(i + 1) for i in range(df.shape[0])])) # Wrong idea wrong way

TypeError: unsupported type: <class 'int'>

In [327]:
df.iloc[1, ::].corr(df.iloc[0, ::])

-0.14868457183059056

In [335]:
df.shape

(8, 10)

In [340]:
[df.iloc[i].corr(df.iloc[i + 1]).round(2) for i in range(df.shape[0])[:-1]]

[-0.15, -0.29, -0.15, -0.03, 0.31, 0.67, 0.28]

In [343]:
df = pd.DataFrame(np.random.randint(1,100, 100).reshape(10, -1))

In [371]:
np.diagonal(df)

array([32, 63, 51,  2,  8, 99, 43, 46, 81, 53])

In [369]:
df.replace(np.diagonal(df), 0)

0   1   2   3   4   5   6   7   8   9
0   0  29  90  56  94  52   0  80  96  77
1  86   0  31  62  56  39   0  68  56  62
2   0  82   0  87  72  40  98  15  59  16
3  22  93  70   0  87  70  54   0  25  47
4  37  72  59  62   0   0  26  14  85  42
5  25   0  17  35  85   0  70  69  39  56
6  30   0  24   0  95   3   0  16   0  70
7  55  89   0  84  67  27  72   0  58  23
8   0  24   0  60  55  76  92  15   0  85
9  76  72  42  95  47  97  67   9  22   0

In [373]:
for i in range(df.shape[0]):
    df.iat[i, i] = 0
    df.iat[df.shape[0]-i-1, i] = 0

In [374]:
df

0   1   2   3   4   5   6   7   8   9
0   0  29  90  56  94  52  63  80  96   0
1  86   0  31  62  56  39  43  68   0  62
2  53  82   0  87  72  40  98   0  59  16
3  22  93  70   0  87  70   0  43  25  47
4  37  72  59  62   0   0  26  14  85  42
5  25  32  17  35   0   0  70  69  39  56
6  30  63  24   0  95   3   0  16  99  70
7  55  89   0  84  67  27  72   0  58  23
8  51   0  63  60  55  76  92  15   0  85
9   0  72  42  95  47  97  67   9  22   0