In [1]:
import numpy as np

In [2]:
np.ones((10, 5)).shape

(10, 5)

In [3]:
np.ones((3, 4, 5), dtype=np.float64).strides

(160, 40, 8)

In [4]:
ints = np.ones(10, dtype=np.uint16)

In [5]:
floats = np.ones(10, dtype=np.float32)

In [6]:
np.issubdtype(ints.dtype, np.integer)

True

In [7]:
np.issubdtype(floats.dtype, np.floating)

True

In [8]:
np.float64.mro()

[numpy.float64,
 numpy.floating,
 numpy.inexact,
 numpy.number,
 numpy.generic,
 float,
 object]

In [9]:
np.issubdtype(ints.dtype, np.number)

True

In [20]:
arr = np.arange(8)

In [21]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [19]:
arr.reshape((4, 3), order='C')

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [22]:
arr.reshape((4, 2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [23]:
arr.reshape((4, 2)).reshape((2, 4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [24]:
arr = np.arange(15)

In [27]:
arr.reshape((5, -1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [28]:
other_arr = np.ones((3, 5))

In [29]:
other_arr.shape

(3, 5)

In [30]:
arr.reshape(other_arr.shape)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [31]:
arr = np.arange(15).reshape((5, 3))

In [32]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [33]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [34]:
arr = np.arange(12).reshape((3, 4))

In [35]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [37]:
arr.ravel('F')

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

In [39]:
arr1 = np.arange(12).reshape((4, 3))

In [42]:
arr2 = np.arange(12).reshape((4, 3), order='F')

In [43]:
arr2

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [44]:
np.concatenate([arr1, arr2], axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [45]:
np.concatenate([arr1, arr2], axis=1)

array([[ 0,  1,  2,  0,  4,  8],
       [ 3,  4,  5,  1,  5,  9],
       [ 6,  7,  8,  2,  6, 10],
       [ 9, 10, 11,  3,  7, 11]])

In [46]:
np.vstack((arr1, arr2))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [47]:
np.hstack((arr1, arr2))

array([[ 0,  1,  2,  0,  4,  8],
       [ 3,  4,  5,  1,  5,  9],
       [ 6,  7,  8,  2,  6, 10],
       [ 9, 10, 11,  3,  7, 11]])

In [48]:
arr = np.random.randn(5, 2)

In [49]:
arr

array([[-1.68540274, -0.43881059],
       [ 0.61700984,  2.02783139],
       [ 1.26318902, -0.09030783],
       [ 1.92175432, -1.26446591],
       [ 0.92530701,  1.29800672]])

In [58]:
first, second, third = np.split(arr, [3, 4])

In [59]:
first

array([[-1.68540274, -0.43881059],
       [ 0.61700984,  2.02783139],
       [ 1.26318902, -0.09030783]])

In [60]:
second

array([[ 1.92175432, -1.26446591]])

In [61]:
third

array([[0.92530701, 1.29800672]])

In [66]:
one, two, three = np.hsplit(arr, [1, 3])

In [67]:
one

array([[-1.68540274],
       [ 0.61700984],
       [ 1.26318902],
       [ 1.92175432],
       [ 0.92530701]])

In [68]:
two

array([[-0.43881059],
       [ 2.02783139],
       [-0.09030783],
       [-1.26446591],
       [ 1.29800672]])

In [69]:
three

array([], shape=(5, 0), dtype=float64)

In [70]:
arr = np.arange(6)

In [71]:
arr1 = arr.reshape((3, 2))

In [72]:
arr2 = np.random.randn(3, 2)

In [73]:
np.r_[arr1, arr2]

array([[ 0.        ,  1.        ],
       [ 2.        ,  3.        ],
       [ 4.        ,  5.        ],
       [ 1.84573809, -0.58905835],
       [-0.64807695, -0.16855902],
       [ 1.08138862,  0.5047766 ]])

In [74]:
np.c_[np.r_[arr1, arr2], arr]

array([[ 0.        ,  1.        ,  0.        ],
       [ 2.        ,  3.        ,  1.        ],
       [ 4.        ,  5.        ,  2.        ],
       [ 1.84573809, -0.58905835,  3.        ],
       [-0.64807695, -0.16855902,  4.        ],
       [ 1.08138862,  0.5047766 ,  5.        ]])

In [75]:
np.c_[1:6, -10:-5]

array([[  1, -10],
       [  2,  -9],
       [  3,  -8],
       [  4,  -7],
       [  5,  -6]])

In [76]:
arr = np.arange(3)

In [77]:
arr

array([0, 1, 2])

In [78]:
arr.repeat(3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [79]:
arr.repeat([2, 3, 4])

array([0, 0, 1, 1, 1, 2, 2, 2, 2])

In [80]:
arr = np.random.randn(2, 2)

In [81]:
arr

array([[0.75653427, 0.01716905],
       [0.49557392, 0.78241138]])

In [82]:
arr.repeat(2, axis=0)

array([[0.75653427, 0.01716905],
       [0.75653427, 0.01716905],
       [0.49557392, 0.78241138],
       [0.49557392, 0.78241138]])

In [83]:
arr.repeat([2, 3], axis=0)

array([[0.75653427, 0.01716905],
       [0.75653427, 0.01716905],
       [0.49557392, 0.78241138],
       [0.49557392, 0.78241138],
       [0.49557392, 0.78241138]])

In [84]:
arr.repeat([2, 3], axis=1)

array([[0.75653427, 0.75653427, 0.01716905, 0.01716905, 0.01716905],
       [0.49557392, 0.49557392, 0.78241138, 0.78241138, 0.78241138]])

In [85]:
arr

array([[0.75653427, 0.01716905],
       [0.49557392, 0.78241138]])

In [86]:
np.tile(arr, 2)

array([[0.75653427, 0.01716905, 0.75653427, 0.01716905],
       [0.49557392, 0.78241138, 0.49557392, 0.78241138]])

In [87]:
arr

array([[0.75653427, 0.01716905],
       [0.49557392, 0.78241138]])

In [88]:
np.tile(arr, (2, 1))

array([[0.75653427, 0.01716905],
       [0.49557392, 0.78241138],
       [0.75653427, 0.01716905],
       [0.49557392, 0.78241138]])

In [89]:
np.tile(arr, (3, 2))

array([[0.75653427, 0.01716905, 0.75653427, 0.01716905],
       [0.49557392, 0.78241138, 0.49557392, 0.78241138],
       [0.75653427, 0.01716905, 0.75653427, 0.01716905],
       [0.49557392, 0.78241138, 0.49557392, 0.78241138],
       [0.75653427, 0.01716905, 0.75653427, 0.01716905],
       [0.49557392, 0.78241138, 0.49557392, 0.78241138]])

In [90]:
arr = np.arange(10) * 100

In [91]:
inds = [7, 1, 2, 6]

In [92]:
arr[inds]

array([700, 100, 200, 600])

In [93]:
arr.take(inds)

array([700, 100, 200, 600])

In [94]:
arr.put(inds, 42)

In [95]:
arr

array([  0,  42,  42, 300, 400, 500,  42,  42, 800, 900])

In [96]:
arr.put(inds, [40, 41, 42, 43])

In [97]:
arr

array([  0,  41,  42, 300, 400, 500,  43,  40, 800, 900])

In [98]:
inds = [2, 0, 2, 1]

In [99]:
arr = np.random.randn(2, 4)

In [100]:
arr

array([[-1.02789576, -0.52383973,  0.58553311, -0.25804362],
       [ 1.8230955 , -0.55469121, -0.8719806 , -1.18627013]])

In [101]:
arr.take(inds, axis=1)

array([[ 0.58553311, -1.02789576,  0.58553311, -0.52383973],
       [-0.8719806 ,  1.8230955 , -0.8719806 , -0.55469121]])